Add call velox simple function test
Intel-bigdata/omniscidb pull request #36
Opened 2021-11-02 03:04 UTC by xieqi

2021-11-18 11:16 UTC, winningsix commented
@Intel-bigdata/bdf-cider-engine

2021-11-19 06:58 UTC, jikunshang approved these changes

2021-11-19 06:58 UTC, jikunshang commented on QueryEngine/RuntimeFunctions.cpp
> +    fprintf(stderr, "call round\n");                                           \
could remove this?

2021-11-19 07:51 UTC, winningsix commented
Will this involve loop dependency here? Velox -> Omnisci -> Velox

Also, we need to make up the missing pieces how Spark/Prestodb functions are registered in Omnisic as well as how functions are called via ```RelAlgExecutionUnit```. Any thoughts for this part?

2022-01-20 00:08 UTC, winningsix requested changes
Two follow ups:
1. Rebase this
2. Handle different implementations in Presto and Spark.

2022-01-20 00:08 UTC, winningsix commented on QueryEngine/ExtensionFunctions.hpp
> +  using funcClass = typename facebook::velox::functions::udf_round<double>::template udf<facebook::velox::core::DynamicExec>;
There're two different implements for Spark and presto in Velox. How can we handle this?
One in prestosql\RegisterArithmetic.cpp and one in sparksql/RegisterArithmetic.cpp

2022-01-25 06:23 UTC, yma11 commented
LGTM. Just remember refine the function related contents in plan doc. Thanks.

2022-01-26 23:27 UTC, winningsix approved these changes
LGTM. Need a rebase before merge.

2022-01-29 00:21 UTC, merged