[DNM][POAE7-1424]Add support for new Velox function via expr/translator/ircodegen
Intel-bigdata/omniscidb pull request #48
Opened 2022-01-06 03:02 UTC by xieqi

2022-01-19 23:42 UTC, winningsix commented
A few follow ups needed:
1. This PR demonstrates a good path from analyzer to Velox function. why marked as DNM?
2. We need to separate supported function untils method. This will also be respected by plan dispatcher. @XinDongIntel
3. @yma11, this needs to touch RelAlgTranslator and also involves expressionRewrite. Do we need to keep expressionRewrite?

2022-01-19 23:43 UTC, winningsix requested changes

2022-01-19 23:43 UTC, winningsix commented on Analyzer/Analyzer.cpp
> +void VeloxFunctionExpr::group_predicates(std::list<const Expr*>& scan_predicates,
Not related to this PR. Just interesting, where is group_predicates used?

2022-01-19 23:43 UTC, winningsix commented on QueryEngine/VeloxFunctionIR.cpp
> +  if (arg0_ti.get_type() == kINT) {
We need decouple this logic here. Frontend rule dispatcher needs this information as well. And those two places need to be consistent.

2022-01-20 01:22 UTC, yma11 commented
> A few follow ups needed:
> 
> 1. This PR demonstrates a good path from analyzer to Velox function. why marked as DNM?
> 2. We need to separate supported function untils method. This will also be respected by plan dispatcher. @XinDongIntel
> 3. @yma11, this needs to touch RelAlgTranslator and also involves expressionRewrite. Do we need to keep expressionRewrite?

My understanding is that RelAlgTranslator is required but expressionRewrite provided here is just a common method of Analyzer::Expr and we won't call it in our code path.

2022-01-24 08:37 UTC, xieqi commented
> A few follow ups needed:
> 
> 1. This PR demonstrates a good path from analyzer to Velox function. why marked as DNM?
As the new function need calcite parser support currently the test will fail, so we can't test this path.

2022-01-24 08:38 UTC, xieqi commented on QueryEngine/VeloxFunctionIR.cpp
> +  if (arg0_ti.get_type() == kINT) {
this is just a demo, you need customized this code according to your function parameters.

2022-01-25 06:22 UTC, yma11 approved these changes
LGTM.

2022-01-26 23:26 UTC, winningsix commented
> > A few follow ups needed:
> > 
> > 1. This PR demonstrates a good path from analyzer to Velox function. why marked as DNM?
> >    As the new function need calcite parser support currently the test will fail, so we can't test this path.

So we suggest to close or refine this?

2022-01-29 00:22 UTC, closed without merging